application:
  host: 127.0.0.1
  port: 8000

database:
  host: "127.0.0.1"
  port: 5432
  username: "emilt"
  password: "123456"
  database_name: "vocsql"
  require_ssl: false

email_client:
  base_url: "localhost"
  sender: "test@gmail.com"
  authorization_token: "123456"
  timeout_milliseconds: 10000

