application:
  host: 0.0.0.0
  port: 8000

database:
  host: "192.168.0.102"
  port: 5432
  username: "emilt"
  password: "123456"
  database_name: "vocsql"
  require_ssl: true

email_client:
  base_url: "https://api.postmarkapp.com"
  sender: voc_sql@voc.com
  authorization_token: "123456"
  timeout_milliseconds: 10000

